services:
  app:
    image: ghcr.io/lhy3944/next4-starter:latest # GHCR 이미지
    container_name: nextjs-stater-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app
